//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonwebApi.Persistance.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class amazonchampEntities1 : DbContext
    {
        public amazonchampEntities1()
            : base("name=amazonchampEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<AddCategory_Result> AddCategory(string category, Nullable<long> parentId)
        {
            var categoryParameter = category != null ?
                new ObjectParameter("category", category) :
                new ObjectParameter("category", typeof(string));
    
            var parentIdParameter = parentId.HasValue ?
                new ObjectParameter("parentId", parentId) :
                new ObjectParameter("parentId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AddCategory_Result>("AddCategory", categoryParameter, parentIdParameter);
        }
    
        public virtual ObjectResult<ChangePassword_Result> ChangePassword(Nullable<System.Guid> userId, string oldPassword, string newPassword, string confirmPassword)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(System.Guid));
    
            var oldPasswordParameter = oldPassword != null ?
                new ObjectParameter("OldPassword", oldPassword) :
                new ObjectParameter("OldPassword", typeof(string));
    
            var newPasswordParameter = newPassword != null ?
                new ObjectParameter("NewPassword", newPassword) :
                new ObjectParameter("NewPassword", typeof(string));
    
            var confirmPasswordParameter = confirmPassword != null ?
                new ObjectParameter("ConfirmPassword", confirmPassword) :
                new ObjectParameter("ConfirmPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChangePassword_Result>("ChangePassword", userIdParameter, oldPasswordParameter, newPasswordParameter, confirmPasswordParameter);
        }
    
        public virtual ObjectResult<ForgetPassword_Result> ForgetPassword(string userName)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ForgetPassword_Result>("ForgetPassword", userNameParameter);
        }
    
        public virtual ObjectResult<GetAbout_Result> GetAbout()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAbout_Result>("GetAbout");
        }
    
        public virtual ObjectResult<GetKeywords_Result> GetKeywords(string keyword, Nullable<long> categoryId)
        {
            var keywordParameter = keyword != null ?
                new ObjectParameter("Keyword", keyword) :
                new ObjectParameter("Keyword", typeof(string));
    
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("CategoryId", categoryId) :
                new ObjectParameter("CategoryId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetKeywords_Result>("GetKeywords", keywordParameter, categoryIdParameter);
        }
    
        public virtual ObjectResult<GetSubscriptionPendingDays_Result> GetSubscriptionPendingDays(Nullable<System.Guid> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSubscriptionPendingDays_Result>("GetSubscriptionPendingDays", userIdParameter);
        }
    
        public virtual ObjectResult<GetSubscriptionPlan_Result> GetSubscriptionPlan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSubscriptionPlan_Result>("GetSubscriptionPlan");
        }
    
        public virtual ObjectResult<GetTemplates_Result> GetTemplates()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTemplates_Result>("GetTemplates");
        }
    
        public virtual ObjectResult<GetUserAbout_Result> GetUserAbout(Nullable<System.Guid> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserAbout_Result>("GetUserAbout", userIdParameter);
        }
    
        public virtual ObjectResult<GetuserAuthorize_Result> GetuserAuthorize(Nullable<System.Guid> userId, string userName)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetuserAuthorize_Result>("GetuserAuthorize", userIdParameter, userNameParameter);
        }
    
        public virtual ObjectResult<GetUserData_Result> GetUserData(Nullable<System.Guid> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserData_Result>("GetUserData", idParameter);
        }
    
        public virtual ObjectResult<GetUserProducts_Result> GetUserProducts(Nullable<System.Guid> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserProducts_Result>("GetUserProducts", userIdParameter);
        }
    
        public virtual ObjectResult<GetUserSubscriptionPlan_Result> GetUserSubscriptionPlan(Nullable<System.Guid> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserSubscriptionPlan_Result>("GetUserSubscriptionPlan", userIdParameter);
        }
    
        public virtual ObjectResult<GetUserTemplates_Result> GetUserTemplates(Nullable<System.Guid> userId, string userName)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserTemplates_Result>("GetUserTemplates", userIdParameter, userNameParameter);
        }
    
        public virtual ObjectResult<LoginAuthenticate_Result> LoginAuthenticate(string username, string password, Nullable<System.DateTime> recordTime)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var recordTimeParameter = recordTime.HasValue ?
                new ObjectParameter("RecordTime", recordTime) :
                new ObjectParameter("RecordTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LoginAuthenticate_Result>("LoginAuthenticate", usernameParameter, passwordParameter, recordTimeParameter);
        }
    
        public virtual ObjectResult<ProductCategory_Result> ProductCategory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductCategory_Result>("ProductCategory");
        }
    
        public virtual ObjectResult<ProductKeywords_Result> ProductKeywords(Nullable<long> id, string keyword, Nullable<long> exactMatchSearchVolume, Nullable<long> broadMatchSearchVolume, Nullable<long> categoryId, Nullable<long> recommendedGiveaway, Nullable<long> hSABid, Nullable<long> exactPPBid, Nullable<long> broadPPCBid, Nullable<long> easeToRank, Nullable<long> relevancyScore, string operation)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(long));
    
            var keywordParameter = keyword != null ?
                new ObjectParameter("Keyword", keyword) :
                new ObjectParameter("Keyword", typeof(string));
    
            var exactMatchSearchVolumeParameter = exactMatchSearchVolume.HasValue ?
                new ObjectParameter("ExactMatchSearchVolume", exactMatchSearchVolume) :
                new ObjectParameter("ExactMatchSearchVolume", typeof(long));
    
            var broadMatchSearchVolumeParameter = broadMatchSearchVolume.HasValue ?
                new ObjectParameter("BroadMatchSearchVolume", broadMatchSearchVolume) :
                new ObjectParameter("BroadMatchSearchVolume", typeof(long));
    
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("CategoryId", categoryId) :
                new ObjectParameter("CategoryId", typeof(long));
    
            var recommendedGiveawayParameter = recommendedGiveaway.HasValue ?
                new ObjectParameter("RecommendedGiveaway", recommendedGiveaway) :
                new ObjectParameter("RecommendedGiveaway", typeof(long));
    
            var hSABidParameter = hSABid.HasValue ?
                new ObjectParameter("HSABid", hSABid) :
                new ObjectParameter("HSABid", typeof(long));
    
            var exactPPBidParameter = exactPPBid.HasValue ?
                new ObjectParameter("ExactPPBid", exactPPBid) :
                new ObjectParameter("ExactPPBid", typeof(long));
    
            var broadPPCBidParameter = broadPPCBid.HasValue ?
                new ObjectParameter("BroadPPCBid", broadPPCBid) :
                new ObjectParameter("BroadPPCBid", typeof(long));
    
            var easeToRankParameter = easeToRank.HasValue ?
                new ObjectParameter("EaseToRank", easeToRank) :
                new ObjectParameter("EaseToRank", typeof(long));
    
            var relevancyScoreParameter = relevancyScore.HasValue ?
                new ObjectParameter("RelevancyScore", relevancyScore) :
                new ObjectParameter("RelevancyScore", typeof(long));
    
            var operationParameter = operation != null ?
                new ObjectParameter("operation", operation) :
                new ObjectParameter("operation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductKeywords_Result>("ProductKeywords", idParameter, keywordParameter, exactMatchSearchVolumeParameter, broadMatchSearchVolumeParameter, categoryIdParameter, recommendedGiveawayParameter, hSABidParameter, exactPPBidParameter, broadPPCBidParameter, easeToRankParameter, relevancyScoreParameter, operationParameter);
        }
    
        public virtual ObjectResult<RagisterUser_Result> RagisterUser(string username, string password, string email, Nullable<System.DateTime> registerationDate)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var registerationDateParameter = registerationDate.HasValue ?
                new ObjectParameter("RegisterationDate", registerationDate) :
                new ObjectParameter("RegisterationDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RagisterUser_Result>("RagisterUser", usernameParameter, passwordParameter, emailParameter, registerationDateParameter);
        }
    
        public virtual ObjectResult<SaveProduct_Result> SaveProduct(string aSIN, Nullable<System.Guid> userId, Nullable<bool> isFeatured, Nullable<long> categoryId, string operation)
        {
            var aSINParameter = aSIN != null ?
                new ObjectParameter("ASIN", aSIN) :
                new ObjectParameter("ASIN", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            var isFeaturedParameter = isFeatured.HasValue ?
                new ObjectParameter("isFeatured", isFeatured) :
                new ObjectParameter("isFeatured", typeof(bool));
    
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("categoryId", categoryId) :
                new ObjectParameter("categoryId", typeof(long));
    
            var operationParameter = operation != null ?
                new ObjectParameter("operation", operation) :
                new ObjectParameter("operation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SaveProduct_Result>("SaveProduct", aSINParameter, userIdParameter, isFeaturedParameter, categoryIdParameter, operationParameter);
        }
    
        public virtual ObjectResult<SaveUserAbout_Result> SaveUserAbout(string aboutTitle, string aboutSummary, Nullable<System.Guid> userId, string address, string phoneNo, string twitter, string facebook, string linkedIn, string logoImage)
        {
            var aboutTitleParameter = aboutTitle != null ?
                new ObjectParameter("AboutTitle", aboutTitle) :
                new ObjectParameter("AboutTitle", typeof(string));
    
            var aboutSummaryParameter = aboutSummary != null ?
                new ObjectParameter("AboutSummary", aboutSummary) :
                new ObjectParameter("AboutSummary", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(System.Guid));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var phoneNoParameter = phoneNo != null ?
                new ObjectParameter("PhoneNo", phoneNo) :
                new ObjectParameter("PhoneNo", typeof(string));
    
            var twitterParameter = twitter != null ?
                new ObjectParameter("Twitter", twitter) :
                new ObjectParameter("Twitter", typeof(string));
    
            var facebookParameter = facebook != null ?
                new ObjectParameter("Facebook", facebook) :
                new ObjectParameter("Facebook", typeof(string));
    
            var linkedInParameter = linkedIn != null ?
                new ObjectParameter("LinkedIn", linkedIn) :
                new ObjectParameter("LinkedIn", typeof(string));
    
            var logoImageParameter = logoImage != null ?
                new ObjectParameter("LogoImage", logoImage) :
                new ObjectParameter("LogoImage", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SaveUserAbout_Result>("SaveUserAbout", aboutTitleParameter, aboutSummaryParameter, userIdParameter, addressParameter, phoneNoParameter, twitterParameter, facebookParameter, linkedInParameter, logoImageParameter);
        }
    
        public virtual ObjectResult<SaveUserSubscriptionPlan_Result> SaveUserSubscriptionPlan(Nullable<System.Guid> userId, Nullable<long> planId, Nullable<decimal> planAmount, Nullable<decimal> payAmount, Nullable<decimal> discount, string currency)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(System.Guid));
    
            var planIdParameter = planId.HasValue ?
                new ObjectParameter("PlanId", planId) :
                new ObjectParameter("PlanId", typeof(long));
    
            var planAmountParameter = planAmount.HasValue ?
                new ObjectParameter("PlanAmount", planAmount) :
                new ObjectParameter("PlanAmount", typeof(decimal));
    
            var payAmountParameter = payAmount.HasValue ?
                new ObjectParameter("PayAmount", payAmount) :
                new ObjectParameter("PayAmount", typeof(decimal));
    
            var discountParameter = discount.HasValue ?
                new ObjectParameter("Discount", discount) :
                new ObjectParameter("Discount", typeof(decimal));
    
            var currencyParameter = currency != null ?
                new ObjectParameter("Currency", currency) :
                new ObjectParameter("Currency", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SaveUserSubscriptionPlan_Result>("SaveUserSubscriptionPlan", userIdParameter, planIdParameter, planAmountParameter, payAmountParameter, discountParameter, currencyParameter);
        }
    
        public virtual ObjectResult<SaveUserTemplate_Result> SaveUserTemplate(Nullable<long> templateId, Nullable<System.Guid> userId, Nullable<bool> @default)
        {
            var templateIdParameter = templateId.HasValue ?
                new ObjectParameter("TemplateId", templateId) :
                new ObjectParameter("TemplateId", typeof(long));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(System.Guid));
    
            var defaultParameter = @default.HasValue ?
                new ObjectParameter("Default", @default) :
                new ObjectParameter("Default", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SaveUserTemplate_Result>("SaveUserTemplate", templateIdParameter, userIdParameter, defaultParameter);
        }
    }
}
